### PR TITLE
Working Forecasting Gui

### PR DESCRIPTION
**Pull request by Alexthw46**
Timestamps are still messed up tho.

Will break asap #121 goes live due to needed key renames. Merge that one first and ping me.

### CODE REVIEW

**Comment by belgio99** [comment]
@Alexthw46 just merged #121

**Review by Degik — APPROVED** [review]

**Comment by Alexthw46** [comment]
Umh, give me time for another commit, the server ain't liking it

**Comment by Degik** [comment]
> Umh, give me time for another commit, the server ain't liking it

Ok

**Comment by Alexthw46** [comment]
honestly i don't understand why it doesn't work. the keys matches the changes done in api

**Comment by Alexthw46** [comment]
I'll merge and investigate on this tonight, I have to check if chat works now

**Comment by Alexthw46** [comment]
Figured it out, Api needs change too

**Pull request merged**
