### PR TITLE
GUI -User settings update & schedule report api

### PR DESCRIPTION
**Pull request by Degik**
GUI update

### CODE REVIEW

**Comment by Alexthw46** [comment]
Don't merge this PR until #38 is finished

**Comment by belgio99** [comment]
@Alexthw46 #38 is merged, shall we merge this as well?

**Comment by Alexthw46** [comment]
We have a small meet soon, but I think we'll merge main into this and retry to hook before unlocking this

**Review by belgio99 — APPROVED** [review]

**Review by Alexthw46 — APPROVED** [review]
Ok then, we'll open a new PR for fixing the hooks later. Let's merge for now.

Reminder that the gui will now require to be authenticated

**Pull request merged**
